name: build

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    # Update references
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Use Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'

    - name: build
      run: |
        npm ci
        npm run convert
        npm run forecast -- ${{ secrets.OPENWEATERHMAP_API_KEY }} 48.5428 16.7606 Zistersdorf openweathermap-zistersdorf
        npm run build


    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      if: github.ref == 'refs/heads/main'
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
